### ISSUE TITLE
The parser seems to be down

### ISSUE THREAD

**Issue by bjrne** [f4lco/om-parser-stw-potsdam-v2#15]
And the linked repository from Kai is either private or deleted... Is there any information on the current situation? :)

**Comment by f4lco** [comment]
Hello @bjrne, always glad to receive a "scream test" on a project  - apparently the parser not working still bothers people 😂 

By taking the parser for a test drive on my machine, the output looks OK - it must be an issue with operations.

I just fixed the typo in the README -  Kai's repo under https://github.com/kaifabian/om-parser-stw-potsdam-v2 is still alive.
The process is basically that development happens in this repo, and on every PR to Kai's, he eyeballs the changes and puts it into prod. So let's raise a ticket with him to check.

**Comment by f4lco** [comment]
Looks like that project has no issues (any longer?) - perhaps a simple mention does the job, @kaifabian? 😄 Can you please check if the deployment is up and healthy?

**Comment by bjrne** [comment]
Haha, it still powers most cafeterias in Brandenburg :sweat_smile: 
Thanks for looking into it so fast, it's not _that_ urgent. The openmensa website states that the last successful crawl was on 26.09.22, so lets see whether tomorrows crawl will be successful or whether @kaifabian reacts :wink:

**Comment by kaifabian** [comment]
Ack, thanks for raising this. Taking a look :)

**Comment by kaifabian** [comment]
Looks like some automated housekeeping just removed the Docker container from my infrastructure. I probably should have some monitoring for that...

Parser should be up & running again.

**Comment by bjrne** [comment]
Perfect, thanks a lot :relaxed:

**Comment by f4lco** [comment]
Thank you so much @kaifabian! 🚀
