### ISSUE TITLE
Might consider switching to unofficial API

### ISSUE THREAD

**Issue by JannisHajda** [f4lco/om-parser-stw-potsdam-v2#16]
Instead of relying on https://www.studentenwerk-potsdam.de/essen/unsere-mensen-cafeterien/detailinfos/, it might be useful to switch to the unofficial API, which can be found at:
https://xml.stw-potsdam.de/xmldata/gs/xml.php
Future website changes shouldn't break the code!

**Comment by f4lco** [comment]
Thank you for the pointer! Who am I to judge which unofficial API is more stable 😉  If you want to get started on an implementation, feel free to file a PR.

**Comment by f4lco** [comment]
Closed as stale. Both URLs of the "unofficial" API are dead by now.
