### ISSUE TITLE
URL and parameters have changed

### ISSUE THREAD

**Issue by felixauringer** [f4lco/om-parser-stw-potsdam-v2#18]
The URL of the stw-potsdam API changed from `/essen/unsere-mensen-cafeterien/detailinfos` to `/essen/unsere-mensen/detailinfos` and the query parameters changed slightly. Currently (also in the latest build), requesting a menu feed causes the parser to crash with a  `JSONDecodeError`.  
The tests do not show this because of 0b630df1b01d57bd9ce55cd720f7708928b86b1d.

**Comment by f4lco** [comment]
Oh dear, the commit message says it all. I was tired of opening the build logs just to find out that the old endpoint did not return JSON on a small percentage of days. If the old endpoint 404ed or something, the [nightly build job](https://app.circleci.com/pipelines/github/f4lco/om-parser-stw-potsdam-v2?branch=master) would have started failing, and would eventually have caught my attention.

Thank you for digging up this repo & for figuring all this out 🏅

**Comment by f4lco** [comment]
I pinged @kaifabian over at https://github.com/kaifabian/om-parser-stw-potsdam-v2/pull/6. He's in charge of deployments 🔧
