### ISSUE TITLE
SWP partly switched to Webspeiseplan; current menu only contains redirect

### ISSUE THREAD

**Issue by adi64** [f4lco/om-parser-stw-potsdam-v2#20]
The Studentenwerk seems to be switching to webspeiseplan.de (https://swp.webspeiseplan.de/Menu). So far e.g. Griebnitzsee still uses the "old" page, but e.g. Filmuniversität uses the new one.

Are you interested in building a new integration? Otherwise I might look into it :)

**Comment by f4lco** [comment]
Hello @adi64 👋  Thanks for raising the issue, and sorry for the late reply - I'm still trailing a bit behind on my emails after my vacation.

Please feel free to take a stab at an implementation, I'd gladly review it and trigger deployment once ready.
So anything goes, we could scrape off webspeiseplan.de, or go with the semi-official API from #16, it still seems to be a thing. Whatever fits the bill best ;)

I'll be happy to see a PR flying by!

**Comment by f4lco** [comment]
Hello @adi64 are you on the topic? If you cannot find the time, could you send another student my way which might take up the project? Thanks!

**Comment by adi64** [comment]
Hey, sorry for the late response. As this is a completely different API, I didn't feel like going for it (until now).
I now have a somewhat working implementation, see here: https://github.com/adi64/om-parser-webspeiseplan.
Also, this thing theoretically works for all other canteens using Webspeiseplan, that's why I changed the repo name. As an example, I added https://iph.webspeiseplan.de/menu (completely unrelated, I just found it online).

It's still WIP though. Some points include
* Tests :joy:
* Linting
* The API token currently seems to be the same for all Webspeiseplan customers :grinning:  It's still configurable per canteen currently. Maybe it would make sense to scrape it off the initial page.
* I could parse the meal sub-categories (e.g. "Essen 1", "Nudeltheke", etc.), but the mappings are in another API endpoint.
* I could parse allergens, additives, etc., but the mappings are in another API endpoint.
* I could parse the location and opening hours, but that is in another API endpoint.
* Price mappings vary between deployments. For the Studentenwerk, `mitarbeiterpreisDecimal2` is for students, `price3Decimal2` is for employees, and `gaestepreisDecimal2` is for guests. This would probably need to be configurable.
* ...? You tell me

I think it could be cool to get this thing productive as early as possible and then refine and add features iteratively. What do you think?

**Comment by f4lco** [comment]
@adi64 I am sorry for the late response - feel free to ping if I fall silent for longer. We received another PR #21, I think it's already in good shape. Let's focus on getting something working again - do you think you could base your efforts on that contribution, and tweak & refine in a "step two"?

**Comment by adi64** [comment]
Fixed with #21. If there is more, I'll look into working on the current state :)
