### ISSUE TITLE
what is the current status?

### ISSUE THREAD

**Issue by fishfacegit** [f4lco/om-parser-stw-potsdam-v2#24]
what is the current status?
Are there still some problems that have to be solved to make it work again?

**Comment by f4lco** [comment]
Unfortunately I do not have news. The transfer of parser ownership on OpenMensa did not happen yet. I am not aware of problems with the parser.
@kaifabian what's the current deployment status? Could you please check if the new parser is up and running?
Happy 2024 everyone!

**Comment by kaifabian** [comment]
Thanks for the ping. Parser ownership in OpenMensa should be transferred now (please check).

Rollout for the new version was stuck (the parser is using a very old, mostly unmonitored part of my infra). After a manual push, the new version seems to be running now.

**Comment by kaifabian** [comment]
New parser fails with the following error(s):
```
Die XML-Daten entsprechen nicht dem Schema des OpenMensa Feed v2.1: 14:0: ERROR: Element '{http://openmensa.org/open-mensa-v2}tuesday', attribute 'open': [facet 'pattern'] The value '08:00 - 15:30 Uhr' is not accepted by the pattern '\d\d:\d\d-\d\d:\d\d'.
```

Will try to write up a quick fix and deploy.

**Comment by fishfacegit** [comment]
ty for updating.
Seems that the MensaApp is working again, i just received a feed via the app on my mobile.
Happy New Year 2024!

**Comment by f4lco** [comment]
> Thanks for the ping. Parser ownership in OpenMensa should be transferred now (please check).

Confirmed, I can see the parser and a wealth of new options and buttons 😂 
Thank you!
